gestor_homepage:
    path:     /
    defaults: { _controller: gestorBundle:Default:index }

all:
        path:     /all
        defaults: { _controller: gestorBundle:Default:all }


conf:
        path:     /conf
        defaults: { _controller: gestorBundle:Default:conf }

profesores:
        path:     /profesores
        defaults: { _controller: gestorBundle:Default:profesores }

crear_empresa:
        path:     /crear
        defaults: { _controller: gestorBundle:Default:crearEmpresa }

new_empresa:
        path:     /new
        defaults: { _controller: gestorBundle:Default:new }

profesores_form:
        path:     /formProfesores
        defaults: { _controller: gestorBundle:Default:formProfesores }

formConf:
        path:     /formConf
        defaults: { _controller: gestorBundle:Default:formConf }


alumnos:
        path:     /alumnos/all
        defaults: { _controller: gestorBundle:Default:alumnos }

api:
  path: /empresa
  defaults:  { _controller: gestorBundle:empresaApi:JSON }
  methods: [GET]

apiProf:
  path: /apiProf
  defaults:  { _controller: gestorBundle:profesoresApi:JSON }
  methods: [GET]
